run:
  timeout: 5m
  skip-dirs:
    - vendor
    - tmp

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - dupl
    - misspell
    - lll
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - gocyclo
    - gocognit
    - godox
    - bodyclose
    - stylecheck
    - revive
    - exportloopref

linters-settings:
  lll:
    line-length: 120
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec