run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - revive

linters-settings:
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-equal
      - name: var-declaration

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
