name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go Mod Download
        run: go mod download

      - name: Go Format Check
        run: |
          files=$(gofmt -l .)
          if [ -n "${files}" ]; then
            echo "Go files not formatted:" >&2
            echo "${files}" >&2
            exit 1
          fi

      - name: Go Vet
        run: go vet ./...

      - name: Run Tests
        run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t init-codex-ci .
